### ISSUE TITLE
Issue: It won't compile

### ISSUE THREAD

**Issue by MajickTek** [MajickTek/JavaPI#1]
Java doesn't want to find any of the math libraries...

**Comment by danbiocchi** [comment]
Fixed it!! Check my commit.

**Comment by MajickTek** [comment]
thanks a lot!

**Comment by MajickTek** [comment]
Wait: sorry, I'm (slightly) new to GitHub.

Where is this commit? I don't see a pull request..?

**Comment by danbiocchi** [comment]
Let me try this again i put it through on desktop. Im new too!

**Comment by MajickTek** [comment]
thanks! I will merge this by copy& paste (since the Pull Request is on your fork), and give credit.

**Comment by MajickTek** [comment]
Fixed, added credits.
